services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "./n8n_data:/home/node/.n8n"
